apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: ClusterIP  # Changed from LoadBalancer to ClusterIP
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
