apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
        - name: frontend
          image: kzizah/yolo-client:1.0.0 # Reference to the Docker image
          ports:
            - containerPort: 3000
