---
# tasks file for gitclone
- name: Clone YOLO repository
  ansible.builtin.git:
        repo: https://github.com/Kzizah/yolo
        dest: "{{ destoyolo }}"
        single_branch: yes
        version: master
    
# Ensure backend directory exists
- name: Ensure backend directory exists
  file:
        path: "{{ destoyolo }}/backend"
        state: directory

# Ensure frontend exists
- name: Ensure client directory exists
  file:
        path: "{{ destoyolo }}/client"
        state: directory